name: Build & Deploy to Github Pages

on:
  push:
    branches: [master]

jobs:
  node-to-gh:
    runs-on: ubuntu-latest
    name: Build & Deploy to Github Pages
    steps:
      - name: Run tests
        run: npm test
        shell: bash 
      - id: node-to-gh
        uses: fdelmazo/node-to-gh-action@v2
