name: Update Horarios

on:
  schedule:
    # Every day at 00:00 GMT-3
    - cron:  "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - run: pip install requests
    - run: pip install jupyter
    - run: pip install nbconvert==6.0.0rc0
    - name: Run Jupy
      run: jupyter nbconvert --to python --execute get_cursos.ipynb
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with: 
        add-paths: src/data/horarios.js
        commit-message: Update horarios [auto]
        delete-branch: true
        title: Actualizar Horarios [auto]
        body: Este PR automático se fijó que los horarios de `ofertahoraria.fi.uba.ar/` cambiaron y los actualizá a la última versión.
        reviewers: FdelMazo, JDSanto
        draft: true



